### ISSUE TITLE
Timing out due to empty character

### ISSUE THREAD

**Issue by Wildhoney** [Pomax/Font.js#28]
It seems that the `printChar` it uses for testing the font is an empty string (`""`).

On [line 425](https://github.com/Pomax/Font.js/blob/master/Font.js#L425):

``` javascript
printChar = String.fromCharCode(endChar);
```

Where `endChar` is `129` for the [following Optima TTF font](https://www.dropbox.com/s/9v1scvq1263s3b4/optima.ttf?dl=0).

I assume the fix in this instance is to detect if the yielded `printChar` is empty, and if so, to revert to the `printChar` default of `A`.

**Comment by Pomax** [comment]
There is already the check to see if the endChar is a printable characters, see https://github.com/Pomax/Font.js/blob/master/Font.js#L412, and from the looks of https://github.com/Pomax/Font.js/blob/master/Font.js#L402 it seems that list is simply missing 0x81 and 0x82 (which are control codes, not actually printable characters) so extending that list with the two codes that are missing should help towards fixing the problem you're experiencing.

**Comment by Pomax** [comment]
https://github.com/Pomax/Font.js/commit/3c8658627c0709e297cc32702fdf01db04a41307 should have fixed this, can you verify this is no longer a problem?

**Comment by Wildhoney** [comment]
Nope &ndash; that didn't fix it. It's now using an `endChar` of `144.

Could you [check the font](https://www.dropbox.com/s/9v1scvq1263s3b4/optima.ttf?dl=0) please to ensure it's not doing something odd?

**Comment by Wildhoney** [comment]
Works when you add `0x0090` to the list:

```javascript
return [0x0009,0x000A,0x000B,0x000C,0x000D,0x0020,0x0081,0x0082,
                  0x0085,0x0090,0x00A0,0x1680,0x180E,0x2000,0x2001,0x2002,
                  0x2003,0x2004,0x2005,0x2006,0x2007,0x2008,0x2009,0x200A,
                  0x2028,0x2029,0x202F,0x205F,0x3000].indexOf(chr) === -1; }
```

Although I'm not sure if that's recommended. With `0x0090` added, the `endChar` is `255` and everything proceeds just fine.

**Comment by Pomax** [comment]
it looks like there's a fair number of control codes missing. https://github.com/Pomax/Font.js/commit/710ea5c7287c41c9cc994c813ecf782110d175f2 adds all reasonable control codes, so with that, things should be fine.

**Comment by Wildhoney** [comment]
:+1: Could you add a `bower.json` when you release next, please?

**Comment by Pomax** [comment]
I'm not a fan of bower, but I can throw it up on npm quite easily (and if you have bower, you have npm already)

**Comment by Wildhoney** [comment]
Don't worry. I'll keep installing it via Bower without the `bower.json` file.

**Comment by Vadimus** [comment]
Got similar issue, chr = 29. Just added condition `chr > 32` to `printable`

**Comment by Pomax** [comment]
Except that is an incorrect condition. Have you tried the latest Font.js from this repo?

**Comment by Pomax** [comment]
obsolete with the 2019 rewrite
