### ISSUE TITLE
Merge with plumin?

### ISSUE THREAD

**Issue by davelab6** [Pomax/Font.js#29]
> I still think JavaScript needs a Font object, but at this point rewriting it from scratch so that it's backed by OpenType.js is far more sensible

You know, http://www.pluminjs.com provides a `Font()` object. Maybe merging the details of this into plumin is best?

**Comment by Pomax** [comment]
Hmm, the "what they do" seems drastically different between the two, though. Plumin is about "an actual font", whereas this `Font` is pretty much identical in function and intended use as the JavaScript `Image` or `Audio`, for font resource loading with event hooks, but that's it. Much like how `Image` won't let you edit the pixels without a canvas, or `Audio` won't let you edit the stream without a jdataview or something, this `Font` won't let you edit the font data without OpenType.js (or Plumin)

**Comment by Pomax** [comment]
obsolete with the 2019 rewrite, which is more of a true parser than a convenience object (even though it _has_ a limited number of convenience functions)
