### ISSUE TITLE
Add instruction on running test/example

### ISSUE THREAD

**Issue by RoelN** [Pomax/Font.js#41]
Because Font.js is loaded as module, it needs to be served instead of being accessed from the filesystem. Maybe add a note explaining this to `index.html`?

(Perhaps including the `python -m SimpleHTTPServer` quick tip?)

Or is there a way to get this going from the file system? Maybe by offering a rolled-up version in a `dist` folder?

**Comment by RoelN** [comment]
By the way, document title is `Tets`

**Comment by Pomax** [comment]
Instructions added.

This was designed specifically to work in the browser, and relies on the Fetch API, so if anyone wants to run this offline/server-side, they'd probably need to fake a browser. I'm not super keen on the idea of writing `if browser elseif node else...` code

**Comment by RoelN** [comment]
Would some quick and dirty swapping of the Fetch API with something like fs be possible?

**Comment by Pomax** [comment]
You can install [node-fetch](https://www.npmjs.com/package/node-fetch) and then require that in as a shim for Fetch, probably.
