### ISSUE TITLE
Errors in README example

### ISSUE THREAD

**Issue by RoelN** [Pomax/Font.js#44]
This doesn't work ("GSUB.lookupList.getSupportedScripts is not a function")

    // Let's figure out which writing scripts this font supports:
    console.log(`This font supports the following scripts: ${
        `"${GSUB.scriptList.getSupportedScripts().join(`", "`)}"`
    }`);

but this does:

    // Let's figure out which writing scripts this font supports:
    console.log(`This font supports the following scripts: ${
        `"${GSUB.getSupportedScripts().join(`", "`)}"`
    }`);

(Removing the `scriptList`).

The `getTable` example errors too (also "is not a function"), couldn't get it to work tweaking the code:

    // DFLT is a given, but let's see if `latn` has any special language/system rules...
    console.log(`Special langsys for "latn": ${
        `"${GSUB.scriptList.getTable('latn').getSupportedLangSys().join(`", "`)}"`
    }`);

**Comment by Pomax** [comment]
Ah yes, I moved most functions to the GSUB table itself (or rather, the opentype common layout table, so they work for both GPOS and GSUB work). Example updated.
