### ISSUE TITLE
Path to simple-table.js

### ISSUE THREAD

**Issue by RoelN** [Pomax/Font.js#46]
![image](https://user-images.githubusercontent.com/4570664/69343683-56c66580-0c6e-11ea-9155-0e0e1481a668.png)

The file is at `src/opentype/tables/simple-table.js` so either move it or change paths everywhere, whatever you intention was?

Also a request for `lazy.js` errors out similarly?

**Comment by Pomax** [comment]
pretty sure my code editor forgot to automatically update the import paths when I was moving files around in the latest commit. Let me fix that right now.

**Comment by Pomax** [comment]
yep, all the paths were wrong =)

fixed.
