### ISSUE TITLE
Get named instances from fvar?

### ISSUE THREAD

**Issue by RoelN** [Pomax/Font.js#53]
A list with name ID and axes values would be useful!

**Comment by Pomax** [comment]
you mean this? https://github.com/Pomax/Font.js/blob/master/src/opentype/tables/simple/variation/fvar.js#L26

**Comment by RoelN** [comment]
That'd get me the axes, but I mean named instances that point to predefined axes settings.

Like the dropdown here:

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/4570664/69609798-a91ad400-102a-11ea-91ed-f2a21db2f390.png">

**Comment by twardoch** [comment]
You have the instances in fvar, they point to name IDs which are in the
name table.

**Comment by Pomax** [comment]
As Adam mentions, the `axisNameID` should let you look that up using:
```
const tables = myFont.opentype.tables;
const axis = tables.fvar.getAxis(`wdth`);
const fullName = tables.name.get(axis.axisNameID)
```

**Comment by RoelN** [comment]
But that gives me _axis_ names, that's a problem indeed solved. I'm looking for _named instances_, the predefined styles that set axes to specific values. I'm not seeing that in the current `fvar` object, or am I missing something obvious?

**Comment by twardoch** [comment]
Pomax's "fvar" starts with "import lazy". Which, I take it, imports from
his soul ;)

Fella only implemented half the table :D

**Comment by Pomax** [comment]
haha, yeah I think I stopped when it turned into "check flags to figure out how to parse the rest". unchecked fvar in https://github.com/Pomax/Font.js/issues/45

**Comment by Pomax** [comment]
alright, instance records added. It's just based on `myfont.opentype.tables.fvar.instances` without special accessors, so you end up mapping that:
```
const { fvar, name } = myFont.opentype.tables;
const instanceNames = fvar.instances.map(instance =>
    name.get(instance.subfamilyNameID)
);
```

**Comment by Pomax** [comment]
That said, it doesn't quite feel like it's doing the right thing, so if you want to help figure that one out: let me know.

**Comment by RoelN** [comment]
🙏 Supermegathanks!! 💖

**Comment by twardoch** [comment]
Maybe Pmax defines "lazy" differently: I'll be adding code when people ask for it, but not before :) That's the good kind of lazy, I'd say ;)

**Comment by Pomax** [comment]
it's the "doing the actual programming" version of lazy loading =D

But on a less joking note, that's kind of true: I started the rewrite for some folks who needed a simple opentype lib, and while adding tables has turned out to be easier than expected, stuff that people actually needed still got done first, with everything that has no one actually asking for it getting done "whenever I feel like it". 

The rewrite's still you, so for now that's still "when I have some dead moments during the day" =)
