### ISSUE TITLE
Testing character throws an error

### ISSUE THREAD

**Issue by eriksachsee** [Pomax/Font.js#57]
In the example there is this line of code:
```
     [`a`, `→`, `嬉`].forEach(char => console.log(`Font supports '${char}': ${
         font.supports(char)
     }`));
```
If it's not commented out, the font won't get loaded.
Message: 

> Event {type: "error", detail: TypeError: this.get is not a function. (In 'this.get(tableID)', 'this.get' is undefined), msg: "Failed to load font at ./fonts/SourceCodeVariable-Roman.otf.woff2", __mayPropagate: true}

If I comment it out, there is no error. But why does it say that the font cant get loaded? How can I test which characters a font file has?

**Comment by Pomax** [comment]
I'd have to see more code than this, because it's missing the code that actually _loads_ the font you're trying to use?

**Comment by Pomax** [comment]
I did a bit of digging based on that error, and it turns out it was a line of code that was using an old function name instead of the new one - I've updated the test cases to cover that code path, and fixed up the code. If you grab the latest master, things should now work.
