### ISSUE TITLE
Make Font.js run on Node.js

### ISSUE THREAD

**Issue by Pomax** [Pomax/Font.js#58]
The main reasons it can't right now is because it relies on window/document. We should be able to shim the functions we need where necessary, and conditionally "just do nothing" if there is no browser context to work in.

What we don't need: "browser bundling" =D

**Comment by Pomax** [comment]
Some tasks:

- [ ] keep things working despite being ES modules (package.json `"type": "module"`)
- [ ] obviate window/document
- [ ] use a fetch api that can load from the filesystem in node context
- [ ] rewrite the existing tests to something jestish
- [ ] have tests work outside the browser

**Comment by RoelN** [comment]
My Kabisa colleague @jnieberg took a stab at this: https://github.com/Pomax/Font.js/pull/62

**Comment by Pomax** [comment]
awsome, I'm in the middle of an all-hands at the moment, but should have lots of time over the weekend to dig in!

**Comment by Pomax** [comment]
I've landed some of this in the codebase already, in a way that lets Node run Font.js from file. The testing I think we agreed to do as separate task, so I'm going to treat those as non-tasks for the purpose of this issue, which means we can close this for now...

**Comment by Pomax** [comment]
as long as the readme shows how to use node, so I'll update that before closing this issue.

**Comment by Pomax** [comment]
https://github.com/Pomax/Font.js/commit/c261e462d7b33e0c577738ee76d93979c3c06ac3
