### ISSUE TITLE
Rollup syntax

### ISSUE THREAD

**Issue by RoelN** [Pomax/Font.js#61]
`npx rollup --no-treeshaking --format=esm Font.js > Font.rolled.js`

should be

`npx rollup --no-treeshake --format=esm Font.js > Font.rolled.js`

At least, On My Machine™

**Comment by RoelN** [comment]
But when loading the rolled version in the browser, I get

`Uncaught SyntaxError: Identifier 'lazy' has already been declared`

**Comment by Pomax** [comment]
rollup doesn't minify by default, so: where in the resulting bundle does that error pop up?
