### ISSUE TITLE
Error handling when loading non-font file

### ISSUE THREAD

**Issue by RoelN** [Pomax/Font.js#63]
In [this line](https://github.com/Pomax/Font.js/blob/master/Font.js#L34), `url` is not defined. Changing it to `path` results in an error related to `dispatch`:

`Font.js:36 Uncaught TypeError: Cannot read property 'dispatch' of undefined`

**Comment by Pomax** [comment]
that should definitely be `path`, the error then talks about the fact that `this.dispatch` apparently doesn't exist, which kind of makes sense, it looks like that function got moved without proper testing.

So we should add one or more tests for loading "not fonts", and then fix that up.

**Comment by Pomax** [comment]
fixed with #97
