### ISSUE TITLE
Handle negative axes values

### ISSUE THREAD

**Issue by RoelN** [Pomax/Font.js#69]
[Recursive](https://github.com/arrowtype/recursive/releases) has a negative MinValue for the Slant axis:

```xml
    <!-- Slant -->
    <Axis>
      <AxisTag>slnt</AxisTag>
      <Flags>0x0</Flags>
      <MinValue>-15.0</MinValue>
      <DefaultValue>0.0</DefaultValue>
      <MaxValue>0.0</MaxValue>
      <AxisNameID>271</AxisNameID>
    </Axis>
```

Font.js returns a `minValue` of 65521. I figure this is because the raw value needs to be interpreted as a signed value. I tried to make it work by using other data types defined in `parser.js`, so I could submit a PR instead of an issue, but had no luck stumbling on a fix by coincidence :-)

**Comment by Pomax** [comment]
That might be a bug in the code for `fixed`, it should be a signed 16.16 value, I wonder if it's parsing as _un_signed 16.16

**Comment by Pomax** [comment]
yep, 100% the culprit: https://github.com/Pomax/Font.js/blob/master/src/parser.js#L74-L78 - want to test that does the right thing when switched to this instead?
```
    get fixed() {
        let major = this.int16;
        let minor = Math.round(1000 * this.uint16/65356);
        return major + minor/1000;
    }
```

**Comment by RoelN** [comment]
That does the trick! 🎉 Made a PR: https://github.com/Pomax/Font.js/pull/70
