### ISSUE TITLE
Get name of feature

### ISSUE THREAD

**Issue by RoelN** [Pomax/Font.js#73]
It would be awesome to get the name if a GSUB/GPOS feature, if a `UINameID` is supplied.

For example Bungee Regular, `ss02` has `UINameID` pointing to ID 256 in the name table, being "Round forms". It would be nice if that is returned by default, or lookupable.

**Comment by Pomax** [comment]
I added in parsing for Feature Parameters, which was missing (I didn't even know that was a thing =D) and added parsing for the three features listed under https://docs.microsoft.com/en-us/typography/opentype/spec/featuretags:

- cc01-cc99
- size (which got superceded by the `STAT` table, but why not, it's only 5 `uint16` anyway)
- ss01-ss99

Running this on the Bungee font, with the following code:

```
import { Font } from "../../Font.js";
const myFont = new Font(`Bungee`);
myFont.onerror = evt => console.error(evt);
myFont.onload = function testFont(evt) {
    const font = evt.detail.font;
    const tables = font.opentype.tables;

    const GSUB = tables.GSUB;
    const ls = GSUB.getLangSysTable(`latn`, `CAT `);
    const features = GSUB.getFeatures(ls);

    features.forEach(feature => {
        if (feature.featureTag.startsWith(`ss`)) {
            const params = feature.getFeatureParams();
            const name = tables.name.get(params.UINameID);
            console.log(`${feature.featureTag} has a name: ${name}`);
        }
    });
}
myFont.src = `./protected/bungee/BungeeColor.ttf`;
```

We get:

```
>node protected\bungee\test.js
ss02 has a name: Round forms
ss03 has a name: Round E
ss04 has a name: Sans-serif I
ss05 has a name: Sans-serif L
ss06 has a name: Alternate ampersand
ss07 has a name: Small quotes
```
