### ISSUE TITLE
COLR table offsets are undefined

### ISSUE THREAD

**Issue by RoelN** [Pomax/Font.js#75]
While testing [Bungee Color](https://github.com/djrrb/Bungee/blob/master/fonts/Bungee_Color_Fonts/BungeeColor-Regular_colr_Windows.ttf) I found that COLR has some offsets set as `undefined`:

```
baseGlyphRecordsOffset: undefined
layerRecordsOffset: undefined
numBaseGlyphRecords: 288
numLayerRecords: 0
version: 0
```

**Comment by Pomax** [comment]
turns out that javascript is case sensitive. WHO KNEW?

https://github.com/Pomax/Font.js/commit/17b969c8f3bab92126fa6916e611383fd07c2203
