### ISSUE TITLE
CPAL doesn't return colors

### ISSUE THREAD

**Issue by RoelN** [Pomax/Font.js#76]
While testing [Bungee Color](https://github.com/djrrb/Bungee/blob/master/fonts/Bungee_Color_Fonts/BungeeColor-Regular_colr_Windows.ttf) I found that the `colorRecord` blue, green, red, alpha values are always 0. These should match the colors defined in the palette.

**Comment by Pomax** [comment]
Investigating the colorRecord parser, we see this:
```
        lazy(this, `colorRecords`, () => {
            p.currentPosition = this.startTable + this.offsetFirstColorRecord;
            console.log(
                `creating ColorRecord starting at ${p.currentPosition},
                from start ${this.startTable} and offset ${this.offsetFirstColorRecord}
            `);
            return [...new Array(this.numColorRecords)].map(_ => new ColorRecord(p));
        });
```
yielding:
```
creating ColorRecord starting at NaN, from start undefined and offset 14
```
so that would certainly cause problems in getting the data out...

**Comment by Pomax** [comment]
https://github.com/Pomax/Font.js/commit/7aa8cee25d1ae53ed1134f232d90e4f0c8eb7b2e
