### ISSUE TITLE
Named instances weirdness

### ISSUE THREAD

**Issue by RoelN** [Pomax/Font.js#78]
If I test with the [Graduate](https://github.com/etunni/Graduate-Variable-Font/blob/master/fonts/variable/GRADUATE.ttf) font, I'm getting the wrong name from the name table. Taking a closer look at `font.opentype.tables.fvar.instances` I see that most `postScriptNameID`s point to 0 or some non-existing name table entry (190, 800). Only the first one properly points to `269` which is the correct ID in the name table for that instance:

```
[
  InstanceRecord {
    subfamilyNameID: 268,
    coordinates: [
      100, 100, 16, 0, 750,
        0, 100,  0, 0, 650,
        0,   0
    ],
    postScriptNameID: 269
  },
  InstanceRecord {
    subfamilyNameID: 0,
    coordinates: [
      0.006,     0, 0, 0.011,
          0, 0.002, 0,     0,
       0.01,     0, 0, 0.004
    ],
    postScriptNameID: 0
  },
  InstanceRecord {
    subfamilyNameID: 100,
    coordinates: [
      800,  16, 0, 750, 0,
      100,   0, 0, 650, 0,
        0, 271
    ],
    postScriptNameID: 190
  },
  InstanceRecord {
    subfamilyNameID: 0,
    coordinates: [
          0, 0, 0.011,     0,
      0.002, 0,     0,  0.01,
          0, 0, 0.004, 0.003
    ],
    postScriptNameID: 0
  },
  InstanceRecord {
    subfamilyNameID: 400,
    coordinates: [
       16,   0, 750, 0, 100,
        0,   0, 650, 0,   0,
      273, 190
    ],
    postScriptNameID: 800
  },
...etc...
```

**Comment by Pomax** [comment]
This smells like the pointers being off, so let's see if we can't figure this out. The data format is listed on https://docs.microsoft.com/en-us/typography/opentype/spec/fvar, and the code is in https://docs.microsoft.com/en-us/typography/opentype/spec/fvar

**Comment by Pomax** [comment]
https://github.com/Pomax/Font.js/commit/95c6ad8bf590ddcfd7f3ae81d77b152dbcb11c8e
